name: ESP-IDF v4.4 Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: ESP-IDF Build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v4.4
        target: esp32s3
        path: '.'
